import io from "socket.io-client";

const socket = io.connect();
var room = "";

//example for useing the creatRoom() function
document.getElementById("join-button").addEventListener("click", createRoom);

function createRoom() {
  //Call this to create a lobby.
  //This will redirect to the subpage, with a link generated by the server.
  //It also moves the client into a socket.io room, which is later used to broadcast the gamechanges to all clients in this lobby / room
  socket.emit("create_room");
  socket.on("room_created", function (data) {
    socket.join(room_link);
    room = room_link;
  });
  location.replace("https://game/" + room_link);
}

function sendChatMessage(message) {
  //This sends the provided string as a message to the lobbys chat
  socket.emit("chat_message", { message: message, room: room });
}
